School.new(name: "Penn St", conference: "Big Ten", wins: 29, losses: 1)
School.new(name: "Florida", conference: "Southeastern",	wins: 25, losses: 1)
School.new(name: "Kentucky", conference: "Southeastern",	wins:26, losses: 1)
School.new(name: "Texas", conference: "Big 12", wins: 24, losses: 2)
School.new(name: "Stanford", conference: "Pac-12", wins:	26, losses: 3)
School.new(name: "Nebraska", conference: "Big Ten", wins:	26, losses: 4)
School.new(name: "Minnesota", conference: "Big Ten", wins:	26, losses: 5)
School.new(name: "Washington", conference: "Pac-12", wins:	24, losses: 7)
School.new(name: "Utah", conference: "Pac-12", wins:	22, losses: 9)
School.new(name: "Southern California", conference:	"Pac-12", wins: 22, losses: 9)
School.new(name: "Baylor", conference: "Big 12", wins:	23, losses: 6)
School.new(name: "Iowa St.", conference: "Big 12", wins:	21, losses: 6)
School.new(name: "Wichita St.", conference: "AAC", wins:28 losses: 3)
School.new(name: "BYU", conference: "West Coast", wins:	28, losses: 2)
School.new(name: "Cal Poly", conference: "Big West" wins: 26, losses: 2)
School.new(name: "UCLA", conference: "Pac-12", wins:	19, losses: 10)
School.new(name: "Wisconsin", conference: "Big Ten", wins: 20, losses: 9)
School.new(name: "Kansas", conference: "Big 12", wins:	22, losses: 7)
School.new(name: "San Diego", conference: "West Coast", wins:	24, losses: 4)
School.new(name: "Louisville", conference: "Atlantic Coast", wins:	24, losses: 6)
School.new(name: "Oregon", conference: "Pac-12", wins:	17, losses: 11)
School.new(name: "Michigan St.", conference: "Big Ten", wins: 21, losses: 8)
School.new(name: "Colorado", conference: "Pac-12", wins:	22, losses: 9)
School.new(name: "Purdue", conference: "Big Ten", wins: 22, losses: 9)
School.new(name: "Illinois", conference: "Big Ten", wins: 21, losses: 10)
